// app/faq/page.tsx
'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { useState } from 'react'

export default function FAQPage() {
    const [openIndex, setOpenIndex] = useState<number | null>(0)

    const faqs = [
        {
            question: "What is Sylvan?",
            answer: "Sylvan is institutional diligence infrastructure that produces standardized sponsor operating records by observing how real estate sponsors perform under real financial obligations before long-term capital is committed.\n\nSylvan does not allocate capital, recommend investments, or rate sponsors. It records what happens under contract and makes that information available for institutional review."
        },
        {
            question: "Does Sylvan invest capital or recommend sponsors?",
            answer: "No. Sylvan does not make allocations, rank sponsors, or provide investment recommendations.\n\nThe platform records sponsor behavior under standardized obligations. Investors and institutions interpret that evidence and make their own decisions."
        },
        {
            question: "How does Sylvan generate sponsor operating records?",
            answer: "Sponsor operating records are generated by placing sponsors under standardized debt obligations with mandatory reporting, payment priority, and disclosure requirements.\n\nBehavior is recorded as obligations are serviced, forecasts are updated, and issues are disclosed, creating a longitudinal operating record rather than a one-time assessment."
        },
        {
            question: "Is Sylvan a marketplace or a fund?",
            answer: "No. Sylvan is neither a marketplace nor a pooled vehicle.\n\nSylvan provides evaluation infrastructure that sits upstream of equity, joint ventures, and programmatic capital relationships."
        },
        {
            question: "Is data and cash flow secure?",
            answer: "Yes. All transactions operate through ring-fenced SPVs and third-party custody.\n\nSylvan does not commingle funds, does not custody investor assets, and does not have discretionary control over capital."
        },
        {
            question: "What does \"behavior under stress\" mean in Sylvan's context?",
            answer: "Stress refers to periods where obligations bind, when payments are due, reserves are tested, forecasts miss, or operating issues arise.\n\nSylvan records how sponsors respond in these moments, not just outcomes when conditions are favorable."
        },
        {
            question: "How is comparability maintained across sponsors?",
            answer: "Comparability is enforced through standardized product frameworks.\n\nWithin each product type, all transactions use identical structures, covenants, reserve rules, and reporting formats, with no sponsor-specific exceptions."
        }
    ]

    const toggleFAQ = (index: number) => {
        setOpenIndex(openIndex === index ? null : index)
    }

    return (
        <main className="min-h-screen bg-[#F3F4F1]">
            {/* Hero Section */}
            <section className="relative py-16 px-6 bg-white overflow-hidden border-b border-gray-200">
                <div className="absolute inset-0 opacity-[0.02]" style={{ backgroundImage: `linear-gradient(rgba(9, 85, 32, 0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(9, 85, 32, 0.3) 1px, transparent 1px)`, backgroundSize: '80px 80px' }} />

                <div className="max-w-4xl mx-auto relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
                        className="text-center"
                    >
                        <h1 className="text-4xl md:text-5xl lg:text-6xl font-medium text-[#095520] mb-4 tracking-tight leading-[1.1]">
                            Frequently Asked Questions
                        </h1>
                        <p className="text-base md:text-lg text-black font-light max-w-2xl mx-auto">
                            Learn more about Sylvan's institutional diligence infrastructure and how we produce standardized sponsor operating records.
                        </p>
                    </motion.div>
                </div>
            </section>

            <section className="bg-[#0A3F28] text-white py-8 px-6 border-l-4 border-[#D9B44A]">
                <div className="max-w-7xl mx-auto">
                    <p className="text-lg italic font-serif leading-relaxed">
                        Sylvan is designed to produce institution-grade evidence through standardized structures and mandatory reporting.
                    </p>
                </div>
            </section>

            {/* FAQ Section */}
            <section className="py-24 px-6 bg-[#0A3F28] relative overflow-hidden">
                {/* Background Geometric Pattern */}
                <div className="absolute top-0 right-0 w-1/3 h-full opacity-5">
                    <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                        <path d="M0,100 L100,0 L100,100 Z" fill="white"/>
                    </svg>
                </div>
                <div className="absolute bottom-0 left-0 w-1/4 h-1/2 opacity-5">
                    <svg width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                        <path d="M0,0 L100,100 L0,100 Z" fill="white"/>
                    </svg>
                </div>

                <div className="max-w-5xl mx-auto relative z-10">
                    <div className="space-y-0 border border-white/10">
                        {faqs.map((faq, index) => (
                            <motion.div
                                key={index}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5, delay: index * 0.05 }}
                                className={`bg-[#0A3F28] ${index !== faqs.length - 1 ? 'border-b border-white/10' : ''}`}
                            >
                                <button
                                    onClick={() => toggleFAQ(index)}
                                    className={`w-full px-8 md:px-12 py-6 md:py-7 text-left flex items-start justify-between gap-6 transition-all duration-200 ${
                                        openIndex === index ? 'bg-white/5' : 'hover:bg-white/[0.03]'
                                    }`}
                                >
                                    <div className="flex items-start gap-4 flex-1">
                                        <span className={`text-xs font-bold uppercase tracking-widest pt-1 transition-colors duration-200 ${
                                            openIndex === index ? 'text-[#D9B44A]' : 'text-[#D9B44A]/50'
                                        }`}>
                                            {String(index + 1).padStart(2, '0')}
                                        </span>
                                        <span className={`text-base md:text-lg font-medium leading-relaxed transition-colors duration-200 ${
                                            openIndex === index ? 'text-white' : 'text-white/80'
                                        }`}>
                                            {faq.question}
                                        </span>
                                    </div>
                                    <div className={`flex-shrink-0 w-10 h-10 flex items-center justify-center border transition-all duration-200 ${
                                        openIndex === index
                                            ? 'border-[#D9B44A] bg-[#D9B44A]'
                                            : 'border-white/20 bg-transparent'
                                    }`}>
                                        <motion.svg
                                            className={`w-4 h-4 transition-colors duration-200 ${
                                                openIndex === index ? 'text-[#0A3F28]' : 'text-white/60'
                                            }`}
                                            animate={{ rotate: openIndex === index ? 180 : 0 }}
                                            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                                            fill="none"
                                            viewBox="0 0 24 24"
                                            stroke="currentColor"
                                            strokeWidth={2.5}
                                        >
                                            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                                        </motion.svg>
                                    </div>
                                </button>

                                <AnimatePresence initial={false}>
                                    {openIndex === index && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                                            className="overflow-hidden bg-white/5"
                                        >
                                            <div className="px-8 md:px-12 pb-7 pt-2">
                                                <div className="pl-8">
                                                    <div className="h-[1px] bg-gradient-to-r from-[#D9B44A]/40 via-[#D9B44A]/10 to-transparent mb-6"></div>
                                                    {faq.answer.split('\n\n').map((paragraph, pIndex) => (
                                                        <p
                                                            key={pIndex}
                                                            className="text-sm md:text-base text-white/70 leading-relaxed font-light mb-4 last:mb-0"
                                                        >
                                                            {paragraph}
                                                        </p>
                                                    ))}
                                                </div>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-24 px-6 bg-[#F3F4F1] border-t border-gray-200">
                <div className="max-w-4xl mx-auto text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
                    >
                        <h2 className="text-2xl md:text-3xl lg:text-4xl font-medium text-[#095520] mb-4 tracking-tight">
                            Still have questions?
                        </h2>
                        <p className="text-base md:text-lg text-black/70 font-light mb-10 max-w-2xl mx-auto">
                            Our team is here to help you understand how Sylvan can support your institutional diligence process.
                        </p>
                        <a
                            href="mailto:contact@sylvan.com"
                            className="inline-block border border-[#013220] px-8 py-3.5 text-sm font-semibold uppercase tracking-wider bg-transparent text-[#013220] hover:bg-[#095520] hover:border-[#095520] hover:text-[#facc15] transition-all duration-200"
                        >
                            Contact Us
                        </a>
                    </motion.div>
                </div>
            </section>
        </main>
    )
}
